//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NoteWhen.rc
//
#define IDC_ADD                         3
#define IDC_DELETE                      4
#define IDC_CHANGE                      4
#define IDC_VIEW_CALENDAR               5
#define IDC_HELPBTN                     6
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_NOTEWHEN_DIALOG             102
#define IDS_SCHEDULE                    102
#define IDS_WHAT                        103
#define IDR_MAINFRAME                   128
#define IDD_PROPERTIES                  130
#define IDR_TRAYMENU                    130
#define IDD_MESSAGE_PAGE                131
#define IDD_MONTH                       132
#define IDB_LOGO                        133
#define IDD_SCHEDULE_PAGE               133
#define IDB_LISTIMAGES                  134
#define IDD_TEXT                        134
#define IDD_SCHEDULE                    135
#define IDC_HAND                        136
#define IDR_NOTEMENU                    143
#define IDC_LIST                        1000
#define IDC_MONTHLY_DAY_NUM             1000
#define IDC_WHEN                        1001
#define IDC_CALENDAR                    1003
#define IDC_DAILY_EVERY                 1004
#define IDC_EDIT1                       1005
#define IDC_DAY                         1005
#define IDC_CHECK1                      1006
#define IDC_DAILY_EVERY_NUM             1006
#define IDC_DISPLAY_NOTE                1006
#define IDC_EDIT2                       1007
#define IDC_SOUND_FILE                  1007
#define IDC_BUTTON1                     1008
#define IDC_BROWSE                      1008
#define IDC_SEARCHBUT                   1008
#define IDC_BUTTON2                     1009
#define IDC_TEST                        1009
#define IDC_EDIT3                       1010
#define IDC_MINUTES                     1010
#define IDC_SPIN1                       1011
#define IDC_HOURS_SPIN                  1011
#define IDC_SPIN2                       1012
#define IDC_MONTHLY_DAY_SPIN            1012
#define IDC_MINUTES_SPIN                1012
#define IDC_SPIN3                       1013
#define IDC_DAILY_DAYS                  1013
#define IDC_DAYS_SPIN                   1013
#define IDC_EDIT4                       1014
#define IDC_MONTHLY_ON_DAY              1014
#define IDC_DAYS                        1014
#define IDC_CHECK2                      1015
#define IDC_MONTHLY_MONTHS              1015
#define IDC_ALWAYS_DISPLAY              1015
#define IDC_TEXT                        1016
#define IDC_WEEKLY_SUNDAY               1016
#define IDC_WEEKLY_MONDAY               1017
#define IDC_WEEKLY_TUESDAY              1018
#define IDC_CHECK3                      1018
#define IDC_NOTIFY_PRIOR                1018
#define IDC_WEEKLY_WEDNESDAY            1019
#define IDC_WEEKLY_THURSDAY             1020
#define IDC_COLOR_SELECT                1020
#define IDC_WEEKLY_FRIDAY               1021
#define IDC_HOURS                       1021
#define IDC_WEEKLY_SATURDAY             1022
#define IDC_ALARM_ENABLED               1022
#define IDC_MONTHLY_JAN                 1023
#define IDC_ENABLE_NOTIFICATIONS        1023
#define IDC_MONTHLY_FEB                 1024
#define IDC_CLOSE                       1024
#define IDC_MONTHLY_MAR                 1025
#define IDC_SEARCHTXT                   1025
#define IDC_MONTHLY_APR                 1026
#define IDC_MONTHLY_MAY                 1027
#define IDC_MONTHLY_JUN                 1028
#define IDC_MONTHLY_JUL                 1029
#define IDC_MONTHLY_AUG                 1030
#define IDC_MONTHLY_SEP                 1031
#define IDC_MONTHLY_OCT                 1032
#define IDC_MONTHLY_NOV                 1033
#define IDC_MONTHLY_DEC                 1034
#define IDC_START_TIME                  1035
#define IDC_DAILY_WEEKDAYS              1036
#define IDC_WEEKLY_EVERY_NUM            1037
#define IDC_WEEKLY_EVERY                1039
#define IDC_WEEKLY_EVERY_SPIN           1040
#define IDC_DAILY_EVERY_SPIN            1042
#define IDC_MONTHLY_ON                  1046
#define IDC_MONTHLY_COUNT               1048
#define IDC_START_DATE                  1049
#define IDC_MONTHLY_DAY                 1050
#define IDC_END_DATE                    1051
#define IDC_WEEKLY_WEEKS                1052
#define IDD_FONTCOLOR                   1543
#define IDD_WHAT_PAGE                   1544
#define IDC_BACKGROUND                  3000
#define ID_HANDLE_EXIT                  32771
#define ID_NOTELIST                     32772
#define ID_DUMMY_ACTIVE                 32773
#define ID_ENABLE                       32773
#define ID_CLOSE                        32775
#define ID_SET_COLORS                   32776
#define ID_SET_SCHEDULE                 32777
#define ID_NEW                          32778
#define ID_DELETE                       32779
#define ID_ALWAYSONTOP                  32780
#define IDM_HELP                        32781
#define ID_BRINGTOTOP                   32782
#define ID_SHOW_ALL                     32783
#define ID_HIDE_ALL                     32784
#define ID_UNDO                         32785
#define ID_SELALL                       32786
#define ID_CUT                          32787
#define ID_COPY                         32788
#define ID_PASTE                        32789
#define ID_CANSTICK                     32792

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
